name: flutter_infrared
description: A new Flutter plugin project.
version: 0.0.1
repository: https://github.com/AlvaroVasconcelos/flutter_infrared

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: dev.vasconcelos.flutter_infrared
        pluginClass: FlutterInfraredPlugin
      ios:
        pluginClass: FlutterInfraredPlugin


